---
  - name: Get infos on container
    docker_container_info:
      name: "{{ grafana_container_name }}"
    register: result
    check_mode: yes

  - name: uninstall Grafana
    import_tasks: uninstall.yml
    when: result.exists == true

  - name: Install Grafana
    import_tasks: install.yml
    when: result.exists == false
