---
  - name: Creating Volumes
    docker_volume:
      name: '{{ item.vol }}'
      labels: {}
      driver_options:
         device: '{{ item.device }}'
         type: none
         o: bind
    loop: "{{vol_loop}}"
