---
  - name: Get infos on container
    docker_container_info:
      name: "{{ elastic_container_name }}"
    register: result
    check_mode: yes

  - name: Install elk stack
    import_tasks: install.yml
    when: result.exists == false
#
  - name: uninstall Nginx
    import_tasks: uninstall.yml
    when: result.exists == true
