---
  - name: Creating Elk stack directory structure
    file:
      path: "{{ elk_default_dir }}/{{ item }}"
      state: directory
      mode: "{{ dir_mode }}"
      recurse: yes
    with_items: "{{ elk_subdir }}"
