---
  - name: Deploy Splunk Search Header container
    docker_container:
      name: "{{ sh_container_name }}"
      hostname: "{{ sh_container_hostname }}"
      image: "{{ splunk_container_image }}"
      state: "{{ splunk_container_state }}"
      restart_policy: "{{ splunk_container_restart_policy }}"
      ports: "{{ sh_container_ports }}"
      env: "{{ splunk.sh.envs }}"
      volumes:
         - "{{ splunk_etc_vol }}"
         - "{{ splunk_var_vol }}"
         - "{{ splunk_driver_vol }}"
         - "{{ splunk_defaults_vol }}"
      networks:
         - name: "{{ cloud_net }}"
           ipv4_address: "{{ ipsplksh }}"
           aliases: "{{ sh_container_name }}"
      purge_networks: yes
