---
  - name: Deploy Splunk Index container
    docker_container:
      name: "{{ idx_container_name }}"
      hostname: "{{ idx_container_hostname }}"
      image: "{{ splunk_container_image }}"
      state: "{{ splunk_container_state }}"
      restart_policy: "{{ splunk_container_restart_policy }}"
      ports: "{{ idx_container_ports }}"
      env: "{{ splunk.idx.envs }}"
      volumes:
         - "{{ splunk_etc_vol }}"
         - "{{ splunk_var_vol }}"
         - "{{ splunk_driver_vol }}"
         - "{{ splunk_defaults_vol }}"
      networks:
         - name: "{{ cloud_net }}"
           ipv4_address: "{{ ipsplkidx }}"
           aliases: "{{ idx_container_name }}"
      purge_networks: yes
