---
  - name: Creating Splunk stack directory structure
    file:
      path: "{{ splunk_default_dir }}/{{ item }}"
      state: directory
      mode: "{{ dir_mode }}"
      recurse: yes
    with_items: "{{ splunk_subdir }}"
