---
  - name: Destroing Splunk Environment container
    docker_container:
      name: "{{ item }}"
      state: absent
      force_kill: yes
    with_items: "{{ splunk_containers }}"

  - name: Deleting directory structure
    file:
      path: "{{splunk_default_dir}}"
      state: absent

  - name: Deleting Volumes
    docker_volume:
      name: '{{ item.vol }}'
      state: absent
    loop: "{{vol_loop}}"
